export enum ErrorCode {
  OK = "OK",
  CONFIG_NOT_FOUND = "CONFIG_NOT_FOUND",
  CONFIG_INVALID = "CONFIG_INVALID",
  VAULT_NOT_FOUND = "VAULT_NOT_FOUND",
  VAULT_NOT_WRITABLE = "VAULT_NOT_WRITABLE",
  VAULT_READ_ONLY = "VAULT_READ_ONLY",
  VAULT_ALREADY_INITIALIZED = "VAULT_ALREADY_INITIALIZED",
  VAULT_EXISTS_NON_EMPTY = "VAULT_EXISTS_NON_EMPTY",
  INIT_PARTIAL = "INIT_PARTIAL",
  PATH_INVALID = "PATH_INVALID",
  PATH_UNSAFE = "PATH_UNSAFE",
  PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND",
  PROJECT_MAP_INVALID = "PROJECT_MAP_INVALID",
  INVALID_SCOPE = "INVALID_SCOPE",
  INVALID_SUMMARY_FILE = "INVALID_SUMMARY_FILE",
  SOURCE_FILE_NOT_FOUND = "SOURCE_FILE_NOT_FOUND",
  RAW_REQUIRES_SOURCE_FILE = "RAW_REQUIRES_SOURCE_FILE",
  SOURCE_NOT_FOUND = "SOURCE_NOT_FOUND",
  TRACE_TARGET_NOT_FOUND = "TRACE_TARGET_NOT_FOUND",
  PROVENANCE_ORPHAN = "PROVENANCE_ORPHAN",
  MARKER_MISSING = "MARKER_MISSING",
  MARKER_INVALID = "MARKER_INVALID",
  WRITE_CONFLICT = "WRITE_CONFLICT",
  BACKUP_FAILED = "BACKUP_FAILED",
  PRIVATE_DATA_RISK = "PRIVATE_DATA_RISK",
  INTEGRATION_UNSUPPORTED = "INTEGRATION_UNSUPPORTED",
  INTEGRATION_NOT_FOUND = "INTEGRATION_NOT_FOUND",
  INTEGRATION_APPLY_FAILED = "INTEGRATION_APPLY_FAILED",
  INTEGRATION_BINARY_UNSTABLE = "INTEGRATION_BINARY_UNSTABLE",
  INTEGRATION_PARTIAL_FAILED = "INTEGRATION_PARTIAL_FAILED",
  FEATURE_UNSUPPORTED = "FEATURE_UNSUPPORTED",
  RUNTIME_UNSUPPORTED = "RUNTIME_UNSUPPORTED",
  NON_INTERACTIVE_REQUIRED = "NON_INTERACTIVE_REQUIRED",
  INIT_CANCELLED = "INIT_CANCELLED",
  WORKTREE_DIRTY = "WORKTREE_DIRTY",
  GIT_REMOTE_UNSUPPORTED = "GIT_REMOTE_UNSUPPORTED",
  BRANCH_POLICY_UNSUPPORTED = "BRANCH_POLICY_UNSUPPORTED",
  TEAM_TARGET_NOT_FOUND = "TEAM_TARGET_NOT_FOUND",
  PROMOTION_NOT_ALLOWED = "PROMOTION_NOT_ALLOWED",
  PROMOTION_PROVIDER_UNSUPPORTED = "PROMOTION_PROVIDER_UNSUPPORTED",
  UNKNOWN_ERROR = "UNKNOWN_ERROR"
}

const exitCodes: Record<ErrorCode, number> = {
  [ErrorCode.OK]: 0,
  [ErrorCode.CONFIG_NOT_FOUND]: 10,
  [ErrorCode.CONFIG_INVALID]: 11,
  [ErrorCode.VAULT_NOT_FOUND]: 12,
  [ErrorCode.VAULT_NOT_WRITABLE]: 13,
  [ErrorCode.VAULT_READ_ONLY]: 14,
  [ErrorCode.VAULT_ALREADY_INITIALIZED]: 15,
  [ErrorCode.VAULT_EXISTS_NON_EMPTY]: 16,
  [ErrorCode.INIT_PARTIAL]: 17,
  [ErrorCode.PATH_INVALID]: 18,
  [ErrorCode.PATH_UNSAFE]: 19,
  [ErrorCode.PROJECT_NOT_FOUND]: 20,
  [ErrorCode.PROJECT_MAP_INVALID]: 21,
  [ErrorCode.INVALID_SCOPE]: 30,
  [ErrorCode.INVALID_SUMMARY_FILE]: 31,
  [ErrorCode.SOURCE_FILE_NOT_FOUND]: 32,
  [ErrorCode.RAW_REQUIRES_SOURCE_FILE]: 33,
  [ErrorCode.SOURCE_NOT_FOUND]: 34,
  [ErrorCode.TRACE_TARGET_NOT_FOUND]: 35,
  [ErrorCode.PROVENANCE_ORPHAN]: 36,
  [ErrorCode.MARKER_MISSING]: 40,
  [ErrorCode.MARKER_INVALID]: 41,
  [ErrorCode.WRITE_CONFLICT]: 42,
  [ErrorCode.BACKUP_FAILED]: 43,
  [ErrorCode.PRIVATE_DATA_RISK]: 50,
  [ErrorCode.INTEGRATION_UNSUPPORTED]: 60,
  [ErrorCode.INTEGRATION_NOT_FOUND]: 61,
  [ErrorCode.INTEGRATION_APPLY_FAILED]: 62,
  [ErrorCode.INTEGRATION_BINARY_UNSTABLE]: 63,
  [ErrorCode.INTEGRATION_PARTIAL_FAILED]: 64,
  [ErrorCode.FEATURE_UNSUPPORTED]: 70,
  [ErrorCode.RUNTIME_UNSUPPORTED]: 71,
  [ErrorCode.NON_INTERACTIVE_REQUIRED]: 72,
  [ErrorCode.INIT_CANCELLED]: 73,
  [ErrorCode.WORKTREE_DIRTY]: 80,
  [ErrorCode.GIT_REMOTE_UNSUPPORTED]: 81,
  [ErrorCode.BRANCH_POLICY_UNSUPPORTED]: 82,
  [ErrorCode.TEAM_TARGET_NOT_FOUND]: 83,
  [ErrorCode.PROMOTION_NOT_ALLOWED]: 84,
  [ErrorCode.PROMOTION_PROVIDER_UNSUPPORTED]: 85,
  [ErrorCode.UNKNOWN_ERROR]: 99
};

export class AgentNotesError extends Error {
  readonly code: ErrorCode;
  readonly exitCode: number;

  constructor(code: ErrorCode, message: string) {
    super(message);
    this.name = "AgentNotesError";
    this.code = code;
    this.exitCode = exitCodeFor(code);
  }
}

export function exitCodeFor(code: ErrorCode): number {
  return exitCodes[code];
}
